sudo: required
services:
    - docker

before_install:
    - docker-compose -f ./expense_tracker/docker-compose-travis.yml up --build

script:
    - docker-compose run python manage.py test

after_success:
#script:
    # Build all images
    - docker build -t thilanse96/expense-tracker-gunicorn ./expense_tracker
    - docker build -t thilanse96/expense-tracker-nginx ./nginx

    # Login to the docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Push the images to Docker Hub
    - docker push thilanse96/expense-tracker-gunicorn
    - docker push thilanse96/expense-tracker-nginx

#deploy:
#    edge: "true"
#    provider: elasticbeanstalk
#    region: us-east-2
#    app: multi-docker
#    env: MultiDocker-env
#    bucket_name: elasticbeanstalk-us-east-2-067269966464
#    bucket_path: docker-multi
#    on:
#        branch: master
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key: $AWS_SECRET_KEY