version: '3.9'

services:
  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: "password"
    volumes:
      - C:\Users\Thilan Senanayake\Documents\expense_tracker_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  django:
    restart: always
    volumes:
      - static:/static
    env_file:
      - .env
    build: ./expense_tracker
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    restart: always
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "8555:80"
    depends_on:
      - django

volumes:
  static: