version: "3.9"
   
services:
  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: "password"
    volumes:
      - C:\Users\Thilan Senanayake\Documents\expense_tracker_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8556:8000"
    depends_on:
      - db