# Generated by Django 3.1.5 on 2021-01-23 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20210123_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date_of_expenditure',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='reason',
            field=models.CharField(max_length=100),
        ),
    ]
