# Generated by Django 3.1.5 on 2021-03-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pending_expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingexpense',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
