# Generated by Django 3.1.5 on 2021-04-25 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_balancer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contributions',
            new_name='Contribution',
        ),
    ]
