# Generated by Django 3.1.5 on 2021-04-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_balancer', '0003_auto_20210425_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
